[package]
name = "alicesaidhi/jabby"
description = "Jecs debugger built with Vide"
version = "0.2.0-rc.9"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["out", ".vscode", "aftman.toml", ".luaurc", "test.project.json", "todo.md", "docs"]
realm = "shared"

[dependencies]
pebble = "alicesaidhi/pebble@0.1.1"
vide = "centau/vide@0.3.1"
jecs = "ukendio/jecs@0.5.3"